---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymlapp
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: predictor
        image: serdarkuyuk/mymlapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
        - containerPort: 80
